# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xf_5pxMCsfMh64wuRtWeyXun7UqUUxJR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Nombre del archivo de texto con la señal EEG de OpenBCI
archivo = "Prueba 4.txt"

# Leer datos del archivo usando pandas
df = pd.read_csv(archivo, sep=',', header=5)
print(df.iloc[:, 4])
x = len(df.iloc[:,4])
xs=30/x
v = round(30/xs)
t = np.linspace(0, 30, v, endpoint=False)
plt.plot(t,df.iloc[:, 4] )
plt.xlabel('Tiempo (s)')
plt.ylabel('Amplitud')
plt.title('Canal 2 cuetionario')
plt.grid(True)
plt.show()

from google.colab import drive
drive.mount('/content/drive')